version: '3'
services:
    pia:
        container_name: pia
        build: ./pia
        image: guoonho/pia-openvpn
        environment:
            - REGION=CA Vancouver
            - USERNAME=p6373449
            - PASSWORD=Dontdropthesoap12!@
        dns:
            - 209.222.18.222
            - 209.222.18.218
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        restart: always

    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - "80:80/tcp"
        environment:
            - NGINX_PORT=80
        restart: unless-stopped

    deluge:
        network_mode: "service:pia"
        container_name: deluge
        image: linuxserver/deluge:amd64-d41d8cd9-ls1
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
            - TZ=America/Vancouver
        volumes:
            - ./deluge:/config
            - /media/babylon/shared/downloads:/downloads
            - /media/babylon/shared/movies:/mnt/movies
            - /media/babylon/shared/tv:/mnt/tv
        restart: unless-stopped

    jellyfin:
        container_name: jellyfin
        image: linuxserver/jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Vancouver
        volumes:
            - ./jellyfin:/config
            - /media/babylon/shared/movies:/data/movies
            - /media/babylon/shared/tv:/data/tvshows
            - /media/babylon/jellyfin:/transcode
        restart: unless-stopped

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Vancouver
        volumes:
            - ./jackett:/config
            - /media/babylon/jackett:/downloads
        restart: unless-stopped

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Vancouver
        volumes:
            - ./sonarr/config:/config
            - /media/babylon/shared/tv:/tv
            - /media/babylon/shared/downloads:/downloads
        restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
              TZ=America/Vancouver
        volumes:
            - ./radarr/config:/config
            - /media/babylon/shared/movies:/movies
            - /media/babylon/shared/downloads:/downloads
        restart: unless-stopped
