version: '3'
services:
    pia:
        container_name: pia
        image: guoonho/pia-openvpn
        env_file: pia.env
        dns:
            - 209.222.18.222
            - 209.222.18.218
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"

    plex:
        image: plexinc/pms-docker
        container_name: plex
        restart: unless-stopped
        env_file: plex.env
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        hostname: kplex
        volumes:
            - /Users/ahboo/docker/plex/config:/config
            - /Users/ahboo/docker/plex/transcode/temp:/transcode
            - /Users/ahboo/docker/plex/media:/data

    transmission:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/transmission
        container_name: transmission
        env_file: trans.env
        volumes:
            - /Users/ahboo/docker/plex/media:/downloads
            - /Users/ahboo/docker/plex/data:/config
            - /Users/ahboo/docker/plex/watch:/watch

    proxy:
        image: dperson/nginx
        container_name: proxy
        ports:
            - 80:80/tcp
            - 443:443/tcp
        links:
            - pia:transmission
            - pia:plex
        command: [
                    "-w", "http://transmission:9091/transmission;/transmission",
                    "-w", "http://plex:32400;/plex" 
                 ]

