version: '3'
services:
    pia:
        container_name: pia
        image: guoonho/pia-openvpn
        env_file: pia.env
        dns:
            - 209.222.18.222
            - 209.222.18.218
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"

    plex:
        image: plexinc/pms-docker
        container_name: plex
        restart: unless-stopped
        env_file: plex.env
        ports:
            - 32400:32400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        hostname: kplex
        volumes:
            - ${MOUNTDIR}/plex/config:/config
            - ${MOUNTDIR}/plex/transcode:/transcode
            - ${MOUNTDIR}/tmp/test/plex/data:/data

    transmission:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/transmission
        container_name: transmission
        env_file: trans.env
        volumes:
            - ${MOUNTDIR}/plex/data:/downloads
            - ${MOUNTDIR}/trans/config:/config
            - ${MOUNTDIR}/trans/watch:/watch

    radarr:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/radarr
        container_name: radarr
        env_file: radarr.env
        volumes:
            - ${MOUNTDIR}/radarr/config:/config
            - ${MOUNTDIR}/plex/data/radarr/downloads:/downloads
            - ${MOUNTDIR}/plex/data/radarr/movies:/movies

    lidarr:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/lidarr
        container_name: lidarr
        env_file: lidarr.env
        volumes:
            - ${MOUNTDIR}/lidarr/music:/music
            - ${MOUNTDIR}/lidarr/config:/config
            - ${MOUNTDIR}/lidarr/downloads:/downloads

    jackett:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/jackett
        container_name: jackett
        env_file: jackett.env
        #ports:
        #    - 9117:9117/tcp
        volumes:
            - ${MOUNTDIR}/jackett/config:/config
            - ${MOUNTDIR}/jackett/blackhole:/downloads

    proxy:
        image: dperson/nginx
        container_name: proxy
        ports:
            - 80:80/tcp
            - 443:443/tcp
        links:
            - pia:transmission
            - pia:radarr
            - pia:lidarr
            - pia:jackett
        command: [
                    "-w", "http://transmission:9091/transmission;/transmission",
                    "-w", "http://radarr:7878/radarr;/radarr",
                    "-w", "http://lidarr:8686/lidarr;/lidarr",
                    "-w", "http://jackett:9117/jackett;/jackett"
                 ]

