version: '3'
services:
    pia:
        container_name: pia
        image: guoonho/pia-openvpn
        env_file: pia.env
        dns:
            - 209.222.18.222
            - 209.222.18.218
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"
        restart: unless-stopped

    transmission:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/transmission
        container_name: transmission
        env_file: trans.env
        volumes:
            - ./trans/config:/config
            - ${MOUNTDIR}/trans/watch:/watch
            - ${MOUNTDIR}/trans/downloads:/downloads
            - ${MOUNTDIR}/shared/movies:/movies
        restart: unless-stopped

    lidarr:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/lidarr
        container_name: lidarr
        env_file: lidarr.env
        volumes:
            - ${MOUNTDIR}/shared/music:/music
            - ./lidarr/config:/config
            - ${MOUNTDIR}/trans/downloads:/downloads
        restart: unless-stopped

    radarr:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/radarr
        container_name: radarr
        env_file: radarr.env
        volumes:
            - ./radarr/config:/config
            - ${MOUNTDIR}/trans/downloads:/downloads
            - ${MOUNTDIR}/shared/movies:/movies
        restart: unless-stopped

    sonarr:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/sonarr
        container_name: sonarr
        env_file: sonarr.env
        volumes:
            - ./sonarr/config:/config
            - ${MOUNTDIR}/trans/downloads:/downloads
            - ${MOUNTDIR}/shared/tv:/tv
        restart: unless-stopped


    jackett:
        network_mode: "service:pia"
        depends_on:
            - "pia"
        image: linuxserver/jackett
        container_name: jackett
        env_file: jackett.env
        volumes:
            - ./jackett/config:/config
            - ${MOUNTDIR}/jackett/downloads:/downloads
        restart: unless-stopped

    emby:
        image: emby/embyserver:4.1.0.12
        container_name: emby
        env_file: emby.env
        volumes:
            - ./emby/config:/config
            - ${MOUNTDIR}/shared/movies:/mnt/movies
            - ${MOUNTDIR}/shared/tv:/mnt/tv
            - ${MOUNTDIR}/emby/transcode:/mnt/transcode
            - ${MOUNTDIR}/emby/cache:/mnt/cache
        restart: unless-stopped

    proxy:
        image: dperson/nginx
        container_name: proxy
        ports:
            - 80:80/tcp
            - 443:443/tcp
            - 9091:9091/tcp
        links:
            - pia:transmission
            - pia:deluge
            - pia:lidarr
            - pia:radarr
            - pia:sonarr
            - pia:jackett
            - emby
        restart: unless-stopped
        command: [
                    "-w", "http://transmission:9091/transmission;/transmission",
                    "-w", "http://radarr:7878/radarr;/radarr",
                    "-w", "http://sonarr:8989/sonarr;/sonarr",
                    "-w", "http://lidarr:8686/lidarr;/lidarr",
                    "-w", "http://jackett:9117/jackett;/jackett",
                    "-w", "http://emby:8096;/emby"
                 ]
